name: MSYS2 Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  msys2_build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          install: >-
            mingw-w64-clang-x86_64-gcc
            mingw-w64-clang-x86_64-pkg-config
            mingw-w64-clang-x86_64-python-cffi
            mingw-w64-clang-x86_64-meson
            mingw-w64-clang-x86_64-gtk2
            mingw-w64-clang-x86_64-gtk-update-icon-cache
            mingw-w64-clang-x86_64-luajit
            mingw-w64-clang-x86_64-desktop-file-utils
            mingw-w64-clang-x86_64-itstool
            mingw-w64-clang-x86_64-gettext-tools
            itstool

      - name: Configure
        run: >-
          meson build
          -Dtext-frontend=true
          -Ddbus=disabled
          -Dwith-upd=false
          -Dwith-perl=false
          -Dwith-python=false
          --prefix=/opt/hexchat

      - name: Build
        run: ninja -C build

      - name: Test
        run: ninja -C build test

      - name: Install
        run: ninja -C build install

      - uses: actions/upload-artifact@v4
        with:
          name: hexchat-clang64
          path: D:/a/_temp/msys64/opt/hexchat/ # or path/to/artifact
